spring:
  profiles:
    active: dev
---
server:
  port: 8100
spring:
  application:
    name: LOGIN-SERVICE
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///aigou
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: com.cn.aigou.domain
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
---
server:
  port: 8001
spring:
  application:
    name: USER-OPERATION
  profiles: dev1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE
  profiles: dev2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///aigou
    username: root
    password: 123456
mybatis-plus:
  type-aliases-package: com.cn.aigou.domain,com.cn.aigou.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka
