spring:
  profiles:
    active: zuul
---
server:
  port: 9527
spring:
  application:
    name: ZUUL-CLIENT
  profiles: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka

